#!/bin/bash 

set -x


(
/usr/bin/xbacklight > /dev/null 2>&1
if [ $? == 0 ]; then
  XBL=`xbacklight -get | cut -d. -f1`
  echo $PIPESTATUS
  if (( $XBL < 10 )); then
    xbacklight -set 100
  fi
fi \
) &
(
pgrep kicker > /dev/null 2>&1
if [ $? == 0 ]; then
  dcop kicker kicker restart
  RET=$?
else
  RET=1
fi
pgrep kdesktop > /dev/null 2>&1
if [[ ($RET != 0) && ($? == 0) ]]; then
  pkill kicker
  sleep 1
  nohup kicker > /dev/null 2>&1
fi
) &
(
WM=`wmctrl -m`
if [[ $WM =~ KWin ]]; then
  nohup kwin --replace > /dev/null 2>&1 &
fi
) &
